### ISSUE TITLE
请求502了？

### ISSUE THREAD

**Issue by wangsuidou** [pomelo-chuan/Zhihu-Daily-Vue.js#2]
![qq 20170207134120](https://cloud.githubusercontent.com/assets/13782434/22679377/a596f994-ed3c-11e6-96b6-b8c2d86c95bc.png)

**Comment by pomelo-chuan** [comment]
刚看了一下，leancloud服务停止运行，重启了一下，现在好了。

**Comment by wangsuidou** [comment]
恩，谢谢哈
