### ISSUE TITLE
服务又挂了？哈哈哈哈

### ISSUE THREAD

**Issue by wangsuidou** [pomelo-chuan/Zhihu-Daily-Vue.js#3]

**Comment by pomelo-chuan** [comment]
我这边能打开唉，你再看看，用的leancloud免费的服务，估计不大稳定

**Comment by landy2014** [comment]
@pomelo-chuan 你nodejs的中转没在git仓库里面，能发来学习一下吗?

**Comment by landy2014** [comment]
呃，网络请求你用的是request，不是axios。

**Comment by pomelo-chuan** [comment]
网页我把node代码放到git里哈

**Comment by pomelo-chuan** [comment]
应该是axios发送了一个request吧，请求都大同小异的，用fetch也可以
