### ISSUE TITLE
安装依赖后不能正常打开

### ISSUE THREAD

**Issue by wayung** [pomelo-chuan/Zhihu-Daily-Vue.js#4]
ERROR  Failed to compile with 1 errors                                 21:30:05

 error  in ./src/pages/Themes.vue

  Vue template syntax error:

  tag <div> has no matching end tag.

**Comment by hackjus** [comment]
错误提示很明显，标签少了一个闭合标签，你看看themes.vue文件在里面加上缺少的闭合标签就可以了！
